# Generated by Django 3.0.5 on 2020-05-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='from_email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(max_length=45),
        ),
    ]
