# Generated by Django 3.0.5 on 2020-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200430_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='accroche',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
