# Generated by Django 3.0.5 on 2020-05-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200430_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='accroche',
            field=models.CharField(default=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='post',
            name='auteur',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
