# Generated by Django 3.0.5 on 2020-05-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200503_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='accroche',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='auteur',
            field=models.CharField(max_length=25),
        ),
    ]
